version: '2'

services:
    task-focus:
        image: u6kapps/task-focus
        volumes:
            - "${DOCKER_VOLUMES}/task-focus/db:/var/lib/task-focus-webapp/hsqldb"
        environment:
            - "VIRTUAL_HOST=task-focus.u6k.me"
            - "VIRTUAL_PORT=8080"
            - "LETSENCRYPT_HOST=task-focus.u6k.me"
            - "LETSENCRYPT_EMAIL=u6k.apps@gmail.com"
        restart: always

networks:
    default:
        external:
            name: nginxproxy_default
