FROM openjdk:8-alpine
LABEL maintainer="u6k.apps@gmail.com"

WORKDIR /usr/local/src/task-focus
VOLUME /usr/local/src/task-focus

ENV _JAVA_OPTIONS="-Duser.timezone=Asia/Tokyo -Duser.country=JP -Duser.language=ja"

EXPOSE 8080
